[tox]
envlist = lint
isolated_build = true

[testenv:lint]
description = Run static type checking and formatting checks
skip_install = true
deps =
    pyright
    isort
    black
commands =
    pyright tixyo
    isort --check-only --diff tixyo
    black --check tixyo
